#!/usr/bin/env python3
"""
Build candidates-review HTML files — interactive browser tools for reviewing
discovery candidates (Tier 2: index terms, Tier 3: LCSH siblings).

Reads:
  - data/index_candidates.json    (Tier 2 back-of-book index candidates)
  - data/lcsh_candidates.json     (Tier 3 LCSH-seeded candidates)
  - data/review_persons.json      (pre-split person candidates)
  - data/review_organizations.json (pre-split organization candidates)
  - data/review_topics.json       (pre-split topic candidates)
  - subject-taxonomy-lcsh.xml     (existing taxonomy for merge targets)
  - taxonomy_review_state.json    (prior decisions, preserved on save)

Writes (depending on --category flag):
  - candidates-review.html              (combined — default, legacy)
  - candidates-review-persons.html      (--category persons)
  - candidates-review-organizations.html (--category organizations)
  - candidates-review-topics.html       (--category topics)
  - all three category files             (--category all)

The generated HTML lets editors:
  - Browse candidates from both discovery tiers
  - Accept candidates (assign to a category)
  - Reject candidates
  - Merge candidates into existing taxonomy terms
  - Filter by source (Index / LCSH), type, status
  - All decisions save to taxonomy_review_state.json (under category-specific keys)

Usage:
    python3 build_candidates_review.py                    # combined (legacy)
    python3 build_candidates_review.py --category persons  # persons only
    python3 build_candidates_review.py --category all      # all 3 category files
"""

import argparse
import json
import os
from datetime import datetime
from lxml import etree

os.chdir(os.path.dirname(os.path.abspath(__file__)))

INDEX_CANDIDATES_FILE = "../data/index_candidates.json"
LCSH_CANDIDATES_FILE = "../data/lcsh_candidates.json"
TAXONOMY_FILE = "../subject-taxonomy-lcsh.xml"
OUTPUT_FILE = "../candidates-review.html"

# Pre-split category files (generated by split_review_categories.py)
CATEGORY_FILES = {
    'persons': '../data/review_persons.json',
    'organizations': '../data/review_organizations.json',
    'topics': '../data/review_topics.json',
}

CATEGORY_OUTPUT_FILES = {
    'persons': '../candidates-review-persons.html',
    'organizations': '../candidates-review-organizations.html',
    'topics': '../candidates-review-topics.html',
}

CATEGORY_TITLES = {
    'persons': 'Person Name Review',
    'organizations': 'Organization & Country Review',
    'topics': 'Topic / Event / Treaty Review',
}

CATEGORY_STATE_KEYS = {
    'persons': 'candidate_decisions_persons',
    'organizations': 'candidate_decisions_organizations',
    'topics': 'candidate_decisions_topics',
}

# Stopwords for keyword-overlap merge matching
_MERGE_STOPWORDS = {
    'the', 'of', 'in', 'and', 'for', 'to', 'a', 'an', 'on', 'with', 'by',
    'from', 'at', 'or', 'as', 'is', 'was', 'be', 'its', 'it', 'not', 'no',
    'but', 'are', 'were', 'that', 'this', 'etc', 'u', 's', 'see', 'also',
    'under', 'united', 'states', 'american', 'between',
}


def _significant_words(text):
    """Extract significant words from a term for keyword matching."""
    words = set(re.sub(r'[^a-z0-9\s]', '', text.lower()).split())
    return words - _MERGE_STOPWORDS - {w for w in words if len(w) < 3}


def compute_merge_suggestions(candidates, existing_subjects):
    """Compute merge suggestions mapping candidate IDs to matching taxonomy terms.

    Returns a dict: candidate_id -> list of {ref, name, match_type, score}.
    Only candidates with at least one match are included.
    """
    # Build normalized lookup for existing subjects
    subj_data = []
    for s in existing_subjects:
        norm = s['name'].lower().strip()
        words = _significant_words(s['name'])
        subj_data.append({
            'ref': s['ref'],
            'name': s['name'],
            'norm': norm,
            'words': words,
        })

    suggestions = {}
    for c in candidates:
        matches = []
        c_norm = c.get('normalized', c['term'].lower().strip())
        c_words = _significant_words(c['term'])

        for s in subj_data:
            # Containment: candidate contains taxonomy term or vice versa
            if len(s['norm']) >= 4 and (s['norm'] in c_norm or c_norm in s['norm']):
                score = 90 if c_norm in s['norm'] else 80
                matches.append({
                    'ref': s['ref'], 'name': s['name'],
                    'matchType': 'containment', 'score': score,
                })
            # Keyword overlap: 2+ shared significant words
            elif len(c_words) >= 2 and len(s['words']) >= 2:
                shared = c_words & s['words']
                if len(shared) >= 2:
                    score = min(70, len(shared) * 20)
                    matches.append({
                        'ref': s['ref'], 'name': s['name'],
                        'matchType': 'keyword', 'score': score,
                    })

        if matches:
            # Deduplicate and sort by score descending, limit to top 10
            seen = set()
            unique = []
            for m in sorted(matches, key=lambda x: -x['score']):
                if m['ref'] not in seen:
                    seen.add(m['ref'])
                    unique.append(m)
            suggestions[c['id']] = unique[:10]

    return suggestions


# Types to exclude from the combined (legacy) review tool.
# These remain in the raw data/index_candidates.json for future use.
EXCLUDED_TYPES = {'country', 'organization'}

# Secondary person-name filter — import from the canonical implementation
# in split_review_categories.py to avoid maintaining duplicate logic.
import re
from split_review_categories import _looks_like_person


def load_candidates():
    """Load and merge candidates from both discovery tiers.

    Filters out countries and organizations — those are outside the scope
    of the subject taxonomy. The raw JSON files retain them for future use
    in a places/organizations index.
    """
    candidates = []

    # Tier 2: Index candidates
    if os.path.exists(INDEX_CANDIDATES_FILE):
        with open(INDEX_CANDIDATES_FILE) as f:
            data = json.load(f)
        for i, c in enumerate(data.get('candidates', [])):
            candidates.append({
                'id': f'idx-{i:04d}',
                'term': c['term'],
                'source': 'index',
                'type': c.get('type', 'topic'),
                'volume_count': c.get('volume_count', 0),
                'doc_count': c.get('doc_count', 0),
                'volumes': c.get('volumes', []),
                'sub_entries': c.get('sub_entries', []),
                'variants': c.get('variants', []),
                'normalized': c.get('normalized', ''),
            })

    # Tier 3: LCSH candidates
    if os.path.exists(LCSH_CANDIDATES_FILE):
        with open(LCSH_CANDIDATES_FILE) as f:
            data = json.load(f)
        for i, c in enumerate(data.get('candidates', [])):
            candidates.append({
                'id': f'lcsh-{i:04d}',
                'term': c['term'],
                'source': 'lcsh',
                'type': 'topic',
                'source_count': c.get('source_count', 0),
                'source_terms': c.get('source_terms', []),
                'lcsh_uri': c.get('lcsh_uri', ''),
                'parent_label': c.get('parent_label', ''),
            })

    # Filter out types outside the subject taxonomy scope
    before = len(candidates)
    candidates = [c for c in candidates if c['type'] not in EXCLUDED_TYPES]
    type_excluded = before - len(candidates)
    if type_excluded:
        print(f"  Filtered out {type_excluded} country/organization entries (kept in raw JSON)")

    # Filter out remaining person names that slipped through discovery heuristics
    before = len(candidates)
    candidates = [c for c in candidates if not _looks_like_person(c['term'])]
    person_excluded = before - len(candidates)
    if person_excluded:
        print(f"  Filtered out {person_excluded} person-name entries (kept in raw JSON)")

    # Filter out malformed entries (embedded doc numbers, excessive whitespace)
    before = len(candidates)
    candidates = [c for c in candidates
                  if not re.search(r',\s*\d{2,3},\s*\n', c['term'])]
    malformed_excluded = before - len(candidates)
    if malformed_excluded:
        print(f"  Filtered out {malformed_excluded} malformed entries")

    return candidates


def load_category_candidates(category):
    """Load pre-split candidates from a category JSON file.

    These files are generated by split_review_categories.py.
    Filters out low-signal entries (< 5 doc hits in a single volume).
    Flags entries needing attention (e.g., truncated treaty names).
    """
    filepath = CATEGORY_FILES[category]
    if not os.path.exists(filepath):
        print(f"  WARNING: {filepath} not found — run split_review_categories.py first")
        return []

    with open(filepath) as f:
        data = json.load(f)

    candidates = data.get('candidates', [])
    print(f"  Loaded {len(candidates)} {category} from {filepath}")

    # Filter out low-signal index entries: < 5 doc hits AND only 1 volume
    # (LCSH candidates don't have doc/volume counts — always keep them)
    before = len(candidates)
    candidates = [c for c in candidates
                  if c.get('source') != 'index'
                  or not (c.get('doc_count', 0) < 5
                          and c.get('volume_count', 0) <= 1)]
    filtered = before - len(candidates)
    if filtered:
        print(f"  Filtered out {filtered} low-signal entries (<5 docs, 1 volume)")

    # Flag entries needing review attention
    for c in candidates:
        flags = []
        term = c.get('term', '')
        # Truncated treaty names ending in "Act of" (missing date)
        if re.search(r'\bAct of\s*$', term):
            flags.append('missing-date')
        if flags:
            c['flags'] = flags

    flagged = sum(1 for c in candidates if c.get('flags'))
    if flagged:
        print(f"  Flagged {flagged} entries for review attention")

    return candidates


def load_taxonomy_categories():
    """Load category structure from taxonomy XML."""
    tree = etree.parse(TAXONOMY_FILE)
    root = tree.getroot()

    categories = {}
    for cat in root.findall('.//category'):
        cat_label = cat.get('label', '')
        subcats = set()
        for subcat in cat.findall('.//subcategory'):
            subcats.add(subcat.get('label', ''))
        categories[cat_label] = sorted(subcats)

    # Also collect all existing subject names for merge-target list
    subjects = []
    for subj in root.findall('.//subject'):
        name_el = subj.find('name')
        if name_el is not None and name_el.text:
            ref = subj.get('ref', '')
            subjects.append({'ref': ref, 'name': name_el.text})

    subjects.sort(key=lambda s: s['name'].lower())
    return categories, subjects


def build_html(candidates, categories, existing_subjects,
               title='Candidate Term Review',
               state_key='candidate_decisions',
               current_category=None,
               merge_suggestions=None):
    """Build the self-contained review HTML.

    Args:
        candidates: List of candidate dicts to embed.
        categories: Dict of taxonomy categories.
        existing_subjects: List of existing subject dicts for merge targets.
        title: Page title shown in the header.
        state_key: Key used in taxonomy_review_state.json for this tool's
                   decisions (e.g., 'candidate_decisions_persons').
        current_category: Which category this tool covers (persons,
                          organizations, topics).  Used for reassign buttons.
        merge_suggestions: Optional dict of candidate_id -> list of merge
                           suggestion objects (from compute_merge_suggestions).
    """
    generated = datetime.now().isoformat()

    # Prepare JSON data
    candidates_json = json.dumps(candidates, ensure_ascii=False)
    categories_json = json.dumps(categories, ensure_ascii=False)
    subjects_json = json.dumps(existing_subjects, ensure_ascii=False)
    merge_suggestions_json = json.dumps(merge_suggestions or {}, ensure_ascii=False)

    # Reassign targets — other categories this tool can send entries to
    all_cats = ['persons', 'organizations', 'topics', 'places']
    reassign_targets = [c for c in all_cats if c != current_category] if current_category else []
    reassign_targets_json = json.dumps(reassign_targets, ensure_ascii=False)
    # Map category name -> state key for reassigned entries
    reassign_state_keys = {c: f'reassigned_to_{c}' for c in all_cats}
    reassign_state_keys_json = json.dumps(reassign_state_keys, ensure_ascii=False)
    current_category_json = json.dumps(current_category or '', ensure_ascii=False)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>FRUS Taxonomy — {title}</title>
<style>
* {{ box-sizing: border-box; margin: 0; padding: 0; }}
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f5f5; color: #333; }}
.header {{ background: #1a365d; color: white; padding: 12px 20px; display: flex; align-items: center; gap: 16px; flex-wrap: wrap; }}
.header h1 {{ font-size: 18px; font-weight: 600; white-space: nowrap; }}
.header .stats {{ font-size: 13px; opacity: 0.85; }}
.toolbar {{ background: #fff; border-bottom: 1px solid #ddd; padding: 10px 20px; display: flex; gap: 12px; align-items: center; flex-wrap: wrap; }}
.toolbar select, .toolbar input {{ padding: 6px 10px; border: 1px solid #ccc; border-radius: 4px; font-size: 13px; }}
.toolbar input[type="search"] {{ width: 220px; }}
.toolbar .filter-group {{ display: flex; align-items: center; gap: 6px; }}
.toolbar label {{ font-size: 12px; color: #666; font-weight: 500; }}

.container {{ display: flex; height: calc(100vh - 110px); }}
.list-pane {{ width: 420px; min-width: 320px; border-right: 1px solid #ddd; background: #fff; overflow-y: auto; }}
.detail-pane {{ flex: 1; overflow-y: auto; padding: 20px; }}

.list-item {{ padding: 10px 14px; border-bottom: 1px solid #eee; cursor: pointer; display: flex; align-items: flex-start; gap: 10px; }}
.list-item:hover {{ background: #f0f4ff; }}
.list-item.selected {{ background: #e8f0fe; border-left: 3px solid #1a73e8; }}
.list-item.decided {{ opacity: 0.5; }}
.list-item .badge {{ font-size: 10px; padding: 2px 6px; border-radius: 10px; font-weight: 600; white-space: nowrap; }}
.badge-index {{ background: #e3f2fd; color: #1565c0; }}
.badge-lcsh {{ background: #f3e5f5; color: #7b1fa2; }}
.badge-country {{ background: #e8f5e9; color: #2e7d32; }}
.badge-org {{ background: #fff3e0; color: #e65100; }}
.badge-treaty {{ background: #fce4ec; color: #c62828; }}
.badge-event {{ background: #fff8e1; color: #f57f17; }}
.badge-topic {{ background: #f5f5f5; color: #616161; }}
.badge-accepted {{ background: #c8e6c9; color: #1b5e20; }}
.badge-rejected {{ background: #ffcdd2; color: #b71c1c; }}
.badge-merged {{ background: #e1bee7; color: #4a148c; }}
.badge-reassigned {{ background: #b3e5fc; color: #01579b; }}
.badge-suggestion {{ background: #fff9c4; color: #f57f17; font-size: 10px; }}
.badge-person {{ background: #ffe0b2; color: #e65100; }}
.badge-place {{ background: #b2dfdb; color: #00695c; }}
.badge-flag {{ background: #ffccbc; color: #bf360c; }}
.badge-org {{ background: #d7ccc8; color: #4e342e; }}

.list-item .term {{ font-weight: 500; font-size: 14px; flex: 1; }}
.list-item .meta {{ font-size: 11px; color: #888; }}
.list-item .status-dot {{ width: 8px; height: 8px; border-radius: 50%; flex-shrink: 0; margin-top: 6px; }}
.dot-pending {{ background: #ccc; }}
.dot-accepted {{ background: #4caf50; }}
.dot-rejected {{ background: #f44336; }}
.dot-merged {{ background: #9c27b0; }}
.dot-reassigned {{ background: #03a9f4; }}
.dot-person {{ background: #ff9800; }}
.dot-place {{ background: #009688; }}
.dot-org {{ background: #795548; }}

.detail-pane h2 {{ font-size: 22px; margin-bottom: 12px; }}
.detail-section {{ background: #fff; border-radius: 8px; padding: 16px; margin-bottom: 16px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }}
.detail-section h3 {{ font-size: 14px; color: #666; margin-bottom: 8px; text-transform: uppercase; letter-spacing: 0.5px; }}
.detail-section p {{ margin: 4px 0; font-size: 14px; }}
.detail-section .volumes {{ font-size: 13px; color: #555; }}
.detail-section .sub-entries {{ font-size: 13px; color: #555; margin-top: 8px; }}
.detail-section .sub-entries li {{ margin: 2px 0 2px 16px; }}

.actions {{ display: flex; gap: 10px; margin: 16px 0; flex-wrap: wrap; }}
.actions button {{ padding: 8px 16px; border: none; border-radius: 6px; font-size: 13px; font-weight: 500; cursor: pointer; }}
.btn-accept {{ background: #4caf50; color: white; }}
.btn-accept:hover {{ background: #388e3c; }}
.btn-reject {{ background: #f44336; color: white; }}
.btn-reject:hover {{ background: #c62828; }}
.btn-merge {{ background: #9c27b0; color: white; }}
.btn-merge:hover {{ background: #7b1fa2; }}
.btn-undo {{ background: #757575; color: white; }}
.btn-undo:hover {{ background: #616161; }}
.btn-reassign {{ background: #0288d1; color: white; font-size: 12px !important; }}
.btn-reassign:hover {{ background: #01579b; }}
.reclass-group {{ display: flex; gap: 6px; margin-left: auto; padding-left: 16px; border-left: 1px solid #ddd; }}

.category-select {{ margin: 12px 0; display: none; }}
.category-select.visible {{ display: flex; gap: 8px; align-items: center; flex-wrap: wrap; }}
.category-select select {{ padding: 6px 10px; border: 1px solid #ccc; border-radius: 4px; }}
.category-select button {{ padding: 6px 12px; background: #1a73e8; color: white; border: none; border-radius: 4px; cursor: pointer; }}

/* Merge modal */
.modal-overlay {{ display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.5); z-index: 100; }}
.modal-overlay.visible {{ display: flex; justify-content: center; align-items: center; }}
.modal {{ background: white; border-radius: 12px; padding: 24px; width: 520px; max-height: 80vh; overflow: hidden; display: flex; flex-direction: column; }}
.modal h3 {{ margin-bottom: 12px; }}
.modal input {{ width: 100%; padding: 8px 12px; border: 1px solid #ccc; border-radius: 4px; margin-bottom: 8px; }}
.modal .merge-list {{ overflow-y: auto; max-height: 50vh; }}
.modal .merge-item {{ padding: 8px 12px; cursor: pointer; border-bottom: 1px solid #eee; }}
.modal .merge-item:hover {{ background: #f0f4ff; }}
.modal .merge-item .name {{ font-weight: 500; }}
.modal .merge-item .ref {{ font-size: 11px; color: #888; }}
.modal-close {{ padding: 8px 16px; background: #eee; border: none; border-radius: 4px; cursor: pointer; margin-top: 12px; }}

.suggestions {{ margin-bottom: 16px; }}
.suggestions h3 {{ font-size: 14px; color: #f57f17; margin-bottom: 8px; text-transform: uppercase; letter-spacing: 0.5px; }}
.suggestion-item {{ display: flex; align-items: center; gap: 10px; padding: 8px 12px; border: 1px solid #fff3e0; border-radius: 6px; margin-bottom: 6px; background: #fffde7; }}
.suggestion-item:hover {{ background: #fff8e1; }}
.suggestion-item .sg-name {{ font-weight: 500; font-size: 14px; flex: 1; }}
.suggestion-item .sg-type {{ font-size: 11px; color: #888; }}
.suggestion-item .sg-btn {{ padding: 4px 12px; background: #9c27b0; color: white; border: none; border-radius: 4px; cursor: pointer; font-size: 12px; white-space: nowrap; }}
.suggestion-item .sg-btn:hover {{ background: #7b1fa2; }}

.empty {{ text-align: center; padding: 40px; color: #999; }}
.save-indicator {{ position: fixed; bottom: 20px; right: 20px; background: #4caf50; color: white; padding: 8px 16px; border-radius: 20px; font-size: 13px; opacity: 0; transition: opacity 0.3s; z-index: 50; }}
.save-indicator.visible {{ opacity: 1; }}
</style>
</head>
<body>

<div class="header">
  <h1>{title}</h1>
  <span class="stats" id="headerStats">Loading...</span>
</div>

<div class="toolbar">
  <div class="filter-group">
    <label>Source:</label>
    <select id="sourceFilter">
      <option value="all">All sources</option>
      <option value="index">Index (Tier 2)</option>
      <option value="lcsh">LCSH (Tier 3)</option>
    </select>
  </div>
  <div class="filter-group">
    <label>Type:</label>
    <select id="typeFilter">
      <option value="all">All types</option>
      <option value="topic">Topics</option>
      <option value="treaty">Treaties</option>
      <option value="event">Events</option>
    </select>
  </div>
  <div class="filter-group">
    <label>Status:</label>
    <select id="statusFilter">
      <option value="pending">Pending</option>
      <option value="all">All</option>
      <option value="accepted">Accepted</option>
      <option value="rejected">Rejected</option>
      <option value="merged">Merged</option>
      <option value="reassigned">Reassigned</option>
      <option value="has-suggestions">Has merge suggestions</option>
      <option value="flagged">Flagged for review</option>
    </select>
  </div>
  <input type="search" id="searchInput" placeholder="Search candidates...">
  <button id="promoteBtn" onclick="promoteDecisions()" style="margin-left:auto; padding:6px 14px; background:#ff6f00; color:white; border:none; border-radius:4px; font-size:13px; font-weight:500; cursor:pointer;">Promote Decisions</button>
  <button id="exportTeiBtn" onclick="exportAllTEI()" style="padding:6px 14px; background:#0d7377; color:white; border:none; border-radius:4px; font-size:13px; font-weight:500; cursor:pointer;">Export All to TEI</button>
</div>

<div class="container">
  <div class="list-pane" id="listPane"></div>
  <div class="detail-pane" id="detailPane">
    <div class="empty">Select a candidate from the list to review it.</div>
  </div>
</div>

<div class="modal-overlay" id="mergeModal">
  <div class="modal">
    <h3>Merge into existing term</h3>
    <input type="search" id="mergeSearch" placeholder="Search taxonomy terms...">
    <div class="merge-list" id="mergeList"></div>
    <button class="modal-close" onclick="closeMergeModal()">Cancel</button>
  </div>
</div>

<div class="save-indicator" id="saveIndicator">Saved</div>

<script>
// ── Data ────────────────────────────────────────────────
let CANDIDATES = {candidates_json};
const CATEGORIES = {categories_json};
const EXISTING_SUBJECTS = {subjects_json};
const MERGE_SUGGESTIONS = {merge_suggestions_json};

// ── Reassign config ─────────────────────────────────────
const CURRENT_CATEGORY = {current_category_json};
const REASSIGN_TARGETS = {reassign_targets_json};
const REASSIGN_STATE_KEYS = {reassign_state_keys_json};
const REASSIGN_LABELS = {{ persons: 'Persons', organizations: 'Organizations', topics: 'Topics', places: 'Places' }};

// ── State ────────────────────────────────────────────────
const STATE_KEY = '{state_key}';
let candidateDecisions = {{}};  // id -> {{action, category, subcategory, mergeTarget, mergeTargetName}}
let selectedId = null;
let saveTimeout = null;

// ── Init ────────────────────────────────────────────────
function init() {{
  loadFromServer();
  document.getElementById('sourceFilter').addEventListener('change', buildList);
  document.getElementById('typeFilter').addEventListener('change', buildList);
  document.getElementById('statusFilter').addEventListener('change', buildList);
  document.getElementById('searchInput').addEventListener('input', debounce(buildList, 200));
  document.getElementById('mergeSearch').addEventListener('input', debounce(filterMergeList, 200));
  buildList();
  updateStats();
}}

function loadFromServer() {{
  fetch('/api/load-taxonomy-decisions')
    .then(r => r.json())
    .then(data => {{
      // Try category-specific key first, fall back to legacy key
      if (data[STATE_KEY]) {{
        candidateDecisions = data[STATE_KEY];
      }} else if (STATE_KEY !== 'candidate_decisions' && data.candidate_decisions) {{
        // Migration: load from legacy key if category key doesn't exist yet
        candidateDecisions = {{}};
        const validIds = new Set(CANDIDATES.map(c => c.id));
        for (const [id, decision] of Object.entries(data.candidate_decisions)) {{
          if (validIds.has(id)) candidateDecisions[id] = decision;
        }}
      }}

      // Inject entries reassigned TO this category from other tools
      if (CURRENT_CATEGORY) {{
        const reassignKey = REASSIGN_STATE_KEYS[CURRENT_CATEGORY];
        const reassigned = data[reassignKey] || [];
        const existingIds = new Set(CANDIDATES.map(c => c.id));
        for (const entry of reassigned) {{
          if (!existingIds.has(entry.id)) {{
            CANDIDATES.push(entry);
            existingIds.add(entry.id);
          }}
        }}
      }}

      buildList();
      updateStats();
    }})
    .catch(e => console.log('Could not load decisions:', e));
}}

// ── List ────────────────────────────────────────────────
function buildList() {{
  const source = document.getElementById('sourceFilter').value;
  const type = document.getElementById('typeFilter').value;
  const status = document.getElementById('statusFilter').value;
  const query = document.getElementById('searchInput').value.toLowerCase();

  let filtered = CANDIDATES.filter(c => {{
    if (source !== 'all' && c.source !== source) return false;
    if (type !== 'all' && c.type !== type) return false;

    const decision = candidateDecisions[c.id];
    const itemStatus = decision ? decision.action : 'pending';
    if (status === 'has-suggestions') {{
      if (!MERGE_SUGGESTIONS[c.id] || MERGE_SUGGESTIONS[c.id].length === 0) return false;
      // Also hide already-decided items when filtering for suggestions
      if (decision) return false;
    }} else if (status === 'flagged') {{
      if (!c.flags || c.flags.length === 0) return false;
      if (decision) return false;
    }} else if (status !== 'all' && itemStatus !== status) return false;

    if (query && !c.term.toLowerCase().includes(query)) return false;
    return true;
  }});

  // Sort by document count descending (most documents first)
  filtered.sort((a, b) => (b.doc_count || 0) - (a.doc_count || 0));

  const pane = document.getElementById('listPane');
  if (filtered.length === 0) {{
    pane.innerHTML = '<div class="empty">No candidates match filters.</div>';
    return;
  }}

  pane.innerHTML = filtered.map(c => {{
    const decision = candidateDecisions[c.id];
    const statusClass = decision ? decision.action : 'pending';
    const decidedClass = decision ? 'decided' : '';
    const selectedClass = c.id === selectedId ? 'selected' : '';
    const sourceBadge = c.source === 'index'
      ? '<span class="badge badge-index">Index</span>'
      : '<span class="badge badge-lcsh">LCSH</span>';
    const typeBadge = c.type !== 'topic'
      ? `<span class="badge badge-${{c.type}}">${{c.type}}</span>`
      : '';
    const statusBadge = decision
      ? `<span class="badge badge-${{decision.action}}">${{decision.action}}</span>`
      : '';
    const reassignedInBadge = c.reassignedFrom
      ? `<span class="badge badge-reassigned">from ${{REASSIGN_LABELS[c.reassignedFrom] || c.reassignedFrom}}</span>`
      : '';
    const suggestionBadge = (MERGE_SUGGESTIONS[c.id] && MERGE_SUGGESTIONS[c.id].length > 0 && !decision)
      ? `<span class="badge badge-suggestion">${{MERGE_SUGGESTIONS[c.id].length}} match${{MERGE_SUGGESTIONS[c.id].length > 1 ? 'es' : ''}}</span>`
      : '';
    const flagBadge = (c.flags && c.flags.length > 0)
      ? c.flags.map(f => `<span class="badge badge-flag">${{f}}</span>`).join('')
      : '';

    let meta = '';
    if (c.source === 'index') {{
      meta = `${{c.volume_count}}v · ${{c.doc_count}}d`;
    }} else {{
      meta = `near ${{c.source_count || 0}} terms`;
    }}

    return `<div class="list-item ${{decidedClass}} ${{selectedClass}}" onclick="selectCandidate('${{c.id}}')">
      <div class="status-dot dot-${{statusClass}}"></div>
      <div style="flex:1">
        <div class="term">${{escapeHtml(c.term)}}</div>
        <div class="meta">${{meta}} ${{sourceBadge}} ${{typeBadge}} ${{reassignedInBadge}} ${{statusBadge}} ${{suggestionBadge}} ${{flagBadge}}</div>
      </div>
    </div>`;
  }}).join('');
}}

// ── Detail ─────────────────────────────────────────────
function selectCandidate(id) {{
  selectedId = id;
  const c = CANDIDATES.find(x => x.id === id);
  if (!c) return;

  const decision = candidateDecisions[id];
  const pane = document.getElementById('detailPane');

  let html = `<h2>${{escapeHtml(c.term)}}</h2>`;

  // Decision status
  if (decision) {{
    html += `<div class="detail-section">
      <h3>Current Decision</h3>
      <p><span class="badge badge-${{decision.action}}">${{decision.action}}</span>`;
    if (decision.action === 'accepted') {{
      html += ` → ${{escapeHtml(decision.category || '?')}} / ${{escapeHtml(decision.subcategory || 'General')}}`;
    }} else if (decision.action === 'merged') {{
      html += ` → ${{escapeHtml(decision.mergeTargetName || '?')}}`;
    }} else if (decision.action === 'reassigned') {{
      html += ` &rarr; ${{escapeHtml(REASSIGN_LABELS[decision.targetCategory] || decision.targetCategory)}}`;
    }} else if (decision.action === 'person') {{
      html += ` — moved to People`;
    }} else if (decision.action === 'place') {{
      html += ` — moved to Places`;
    }} else if (decision.action === 'org') {{
      html += ` — moved to Organizations`;
    }}
    html += `</p>
      <button class="btn-undo" onclick="undoDecision('${{id}}')">Undo</button>
    </div>`;
  }}

  // Actions
  const reassignBtns = REASSIGN_TARGETS.map(cat =>
    `<button class="btn-reassign btn-reassign-${{cat}}" onclick="reassignToCategory('${{id}}','${{cat}}')">&rarr; ${{REASSIGN_LABELS[cat]}}</button>`
  ).join('');
  html += `<div class="actions">
    <button class="btn-accept" onclick="showAcceptPanel('${{id}}')">Accept</button>
    <button class="btn-reject" onclick="rejectCandidate('${{id}}')">Reject</button>
    <button class="btn-merge" onclick="openMergeModal('${{id}}')">Merge Into...</button>
    ${{reassignBtns ? `<div class="reclass-group">${{reassignBtns}}</div>` : ''}}
  </div>`;

  // Suggested merges section
  const suggestions = MERGE_SUGGESTIONS[id] || [];
  if (suggestions.length > 0) {{
    html += `<div class="detail-section suggestions">
      <h3>Suggested Merges (${{suggestions.length}})</h3>`;
    suggestions.forEach(s => {{
      const matchLabel = s.matchType === 'containment' ? 'substring' : 'keywords';
      html += `<div class="suggestion-item">
        <div class="sg-name">${{escapeHtml(s.name)}}</div>
        <div class="sg-type">${{matchLabel}}</div>
        <button class="sg-btn" onclick="confirmMerge('${{s.ref}}', '${{escapeHtml(s.name).replace(/'/g, "\\\\'")}}')">Merge</button>
      </div>`;
    }});
    html += `</div>`;
  }}

  // Category select (hidden until Accept clicked)
  const catOptions = Object.keys(CATEGORIES).sort().map(cat =>
    `<option value="${{escapeHtml(cat)}}">${{escapeHtml(cat)}}</option>`
  ).join('');
  html += `<div class="category-select" id="catSelect">
    <select id="catDropdown">${{catOptions}}</select>
    <select id="subcatDropdown"><option value="General">General</option></select>
    <button onclick="confirmAccept('${{id}}')">Confirm</button>
  </div>`;

  // Source info
  html += `<div class="detail-section">
    <h3>Source</h3>
    <p>Discovery tier: ${{c.source === 'index' ? 'Tier 2 — Back-of-book Index' : 'Tier 3 — LCSH Expansion'}}</p>
    <p>Type: ${{c.type}}</p>`;

  if (c.source === 'index') {{
    html += `<p>Appears in ${{c.volume_count}} volume index${{c.volume_count !== 1 ? 'es' : ''}}, referencing ${{c.doc_count}} documents</p>`;
    if (c.volumes && c.volumes.length) {{
      html += `<p class="volumes">Volumes: ${{c.volumes.join(', ')}}</p>`;
    }}
    if (c.sub_entries && c.sub_entries.length) {{
      html += `<div class="sub-entries"><strong>Index sub-entries:</strong><ul>`;
      c.sub_entries.forEach(se => {{
        html += `<li>${{escapeHtml(se)}}</li>`;
      }});
      html += `</ul></div>`;
    }}
    if (c.variants && c.variants.length > 1) {{
      html += `<p>Variants: ${{c.variants.map(v => escapeHtml(v)).join('; ')}}</p>`;
    }}
  }} else {{
    if (c.source_count) {{
      html += `<p>Appeared near ${{c.source_count}} existing taxonomy terms</p>`;
    }}
    if (c.source_terms && c.source_terms.length) {{
      html += `<p>Nearby terms: ${{c.source_terms.map(t => escapeHtml(t)).join(', ')}}</p>`;
    }}
    if (c.lcsh_uri) {{
      html += `<p>LCSH: <a href="${{c.lcsh_uri}}" target="_blank">${{escapeHtml(c.lcsh_uri)}}</a></p>`;
    }}
    if (c.parent_label) {{
      html += `<p>LCSH parent: ${{escapeHtml(c.parent_label)}}</p>`;
    }}
  }}

  html += `</div>`;
  pane.innerHTML = html;

  // Wire up category dropdown change
  const catDd = document.getElementById('catDropdown');
  if (catDd) {{
    catDd.addEventListener('change', updateSubcatDropdown);
  }}

  buildList();
}}

function showAcceptPanel(id) {{
  const panel = document.getElementById('catSelect');
  if (panel) panel.classList.add('visible');
  updateSubcatDropdown();
}}

function updateSubcatDropdown() {{
  const cat = document.getElementById('catDropdown').value;
  const subcats = CATEGORIES[cat] || ['General'];
  const dd = document.getElementById('subcatDropdown');
  dd.innerHTML = subcats.map(sc =>
    `<option value="${{escapeHtml(sc)}}">${{escapeHtml(sc)}}</option>`
  ).join('');
  if (!subcats.includes('General')) {{
    dd.innerHTML = '<option value="General">General</option>' + dd.innerHTML;
  }}
}}

function confirmAccept(id) {{
  const cat = document.getElementById('catDropdown').value;
  const subcat = document.getElementById('subcatDropdown').value;
  candidateDecisions[id] = {{
    action: 'accepted',
    category: cat,
    subcategory: subcat,
    term: CANDIDATES.find(c => c.id === id)?.term || '',
  }};
  autoSave();
  selectCandidate(id);
  updateStats();
}}

function rejectCandidate(id) {{
  candidateDecisions[id] = {{
    action: 'rejected',
    term: CANDIDATES.find(c => c.id === id)?.term || '',
  }};
  autoSave();
  advanceToNext(id);
  updateStats();
}}

function reassignToCategory(id, targetCategory) {{
  const candidate = CANDIDATES.find(c => c.id === id);
  if (!candidate) return;
  candidateDecisions[id] = {{
    action: 'reassigned',
    targetCategory: targetCategory,
    term: candidate.term,
  }};
  // Store the full candidate in a pending reassign queue (written on save)
  if (!window._pendingReassignments) window._pendingReassignments = [];
  window._pendingReassignments.push({{
    targetCategory,
    candidate: {{ ...candidate, id: `reassign-${{CURRENT_CATEGORY}}-${{id}}`, reassignedFrom: CURRENT_CATEGORY }},
  }});
  autoSave();
  advanceToNext(id);
  updateStats();
}}

function undoDecision(id) {{
  delete candidateDecisions[id];
  autoSave();
  selectCandidate(id);
  updateStats();
}}

function advanceToNext(currentId) {{
  // Find the next pending candidate in the filtered list
  const source = document.getElementById('sourceFilter').value;
  const type = document.getElementById('typeFilter').value;
  const query = document.getElementById('searchInput').value.toLowerCase();

  const pending = CANDIDATES.filter(c => {{
    if (c.id === currentId) return false;
    if (source !== 'all' && c.source !== source) return false;
    if (type !== 'all' && c.type !== type) return false;
    if (query && !c.term.toLowerCase().includes(query)) return false;
    const d = candidateDecisions[c.id];
    return !d;  // only pending
  }});

  if (pending.length > 0) {{
    selectCandidate(pending[0].id);
  }} else {{
    selectCandidate(currentId);
  }}
}}

// ── Merge modal ────────────────────────────────────────
let mergeSourceId = null;

function openMergeModal(id) {{
  mergeSourceId = id;
  document.getElementById('mergeModal').classList.add('visible');
  document.getElementById('mergeSearch').value = '';
  filterMergeList();
  document.getElementById('mergeSearch').focus();
}}

function closeMergeModal() {{
  document.getElementById('mergeModal').classList.remove('visible');
  mergeSourceId = null;
}}

function filterMergeList() {{
  const query = document.getElementById('mergeSearch').value.toLowerCase();
  const filtered = query
    ? EXISTING_SUBJECTS.filter(s => s.name.toLowerCase().includes(query))
    : EXISTING_SUBJECTS.slice(0, 50);

  document.getElementById('mergeList').innerHTML = filtered.map(s =>
    `<div class="merge-item" onclick="confirmMerge('${{s.ref}}', '${{escapeHtml(s.name).replace(/'/g, "\\\\'")}}')">
      <div class="name">${{escapeHtml(s.name)}}</div>
      <div class="ref">${{s.ref}}</div>
    </div>`
  ).join('');
}}

function confirmMerge(targetRef, targetName) {{
  const sourceId = mergeSourceId || selectedId;
  if (!sourceId) return;
  candidateDecisions[sourceId] = {{
    action: 'merged',
    mergeTarget: targetRef,
    mergeTargetName: targetName,
    term: CANDIDATES.find(c => c.id === sourceId)?.term || '',
  }};
  closeMergeModal();
  autoSave();
  selectCandidate(sourceId);
  updateStats();
}}

// ── Save ────────────────────────────────────────────────
function autoSave() {{
  clearTimeout(saveTimeout);
  saveTimeout = setTimeout(saveToServer, 1500);
}}

function saveToServer() {{
  // Load existing state first to preserve other decisions
  fetch('/api/load-taxonomy-decisions')
    .then(r => r.json())
    .then(existing => {{
      const payload = {{
        ...existing,
        [STATE_KEY]: candidateDecisions,
      }};

      // Flush pending reassignments into target category arrays
      const pending = window._pendingReassignments || [];
      for (const item of pending) {{
        const key = REASSIGN_STATE_KEYS[item.targetCategory];
        if (!payload[key]) payload[key] = [];
        // Avoid duplicates
        const existingIds = new Set(payload[key].map(e => e.id));
        if (!existingIds.has(item.candidate.id)) {{
          payload[key].push(item.candidate);
        }}
      }}
      window._pendingReassignments = [];

      return fetch('/api/save-taxonomy-decisions', {{
        method: 'POST',
        headers: {{'Content-Type': 'application/json'}},
        body: JSON.stringify(payload),
      }});
    }})
    .then(r => r.json())
    .then(data => {{
      const indicator = document.getElementById('saveIndicator');
      indicator.classList.add('visible');
      setTimeout(() => indicator.classList.remove('visible'), 2000);
    }})
    .catch(e => console.error('Save failed:', e));
}}

// ── Promote ─────────────────────────────────────────────
function promoteDecisions() {{
  const btn = document.getElementById('promoteBtn');
  btn.disabled = true;
  btn.textContent = 'Promoting...';
  btn.style.background = '#999';

  fetch('/api/promote-candidates', {{ method: 'POST' }})
    .then(response => response.text())
    .then(text => {{
      // Parse SSE lines to find final status
      const lines = text.split('\\n').filter(l => l.startsWith('data: '));
      const lastLine = lines[lines.length - 1] || '';
      let success = false;
      try {{
        const msg = JSON.parse(lastLine.replace('data: ', ''));
        success = msg.status === 'success';
      }} catch(e) {{}}

      // Find output summary
      const outputLines = lines
        .map(l => {{ try {{ return JSON.parse(l.replace('data: ', '')); }} catch(e) {{ return null; }} }})
        .filter(m => m && m.type === 'output' && m.line)
        .map(m => m.line);

      if (success) {{
        const summary = outputLines.find(l => l.includes('variant')) || 'Promoted!';
        btn.textContent = summary.slice(0, 45);
        btn.style.background = '#4caf50';
      }} else {{
        btn.textContent = 'Failed — check console';
        btn.style.background = '#f44336';
        console.error('Promote output:', outputLines.join('\\n'));
      }}
      setTimeout(() => {{
        btn.textContent = 'Promote Decisions';
        btn.style.background = '#ff6f00';
        btn.disabled = false;
      }}, 4000);
    }})
    .catch(e => {{
      btn.textContent = 'Error!';
      btn.style.background = '#f44336';
      console.error('Promote failed:', e);
      setTimeout(() => {{
        btn.textContent = 'Promote Decisions';
        btn.style.background = '#ff6f00';
        btn.disabled = false;
      }}, 3000);
    }});
}}

// ── Export to TEI ────────────────────────────────────────
function exportAllTEI() {{
  if (!confirm('Export reviewed decisions to TEI headers for ALL reviewed volumes?\\n\\nThis will write accepted subject annotations into each document\\'s TEI header. Candidates must be promoted first. This may take a while.')) return;
  const btn = document.getElementById('exportTeiBtn');
  btn.disabled = true;
  btn.textContent = 'Exporting...';
  btn.style.background = '#999';

  fetch('/api/export-tei-headers-all', {{ method: 'POST' }})
    .then(response => response.text())
    .then(text => {{
      const lines = text.split('\\n').filter(l => l.startsWith('data: '));
      const lastLine = lines[lines.length - 1] || '';
      let success = false;
      try {{
        const msg = JSON.parse(lastLine.replace('data: ', ''));
        success = msg.status === 'success';
      }} catch(e) {{}}

      const outputLines = lines
        .map(l => {{ try {{ return JSON.parse(l.replace('data: ', '')); }} catch(e) {{ return null; }} }})
        .filter(m => m && m.type === 'output' && m.line)
        .map(m => m.line);

      if (success) {{
        const summary = outputLines.find(l => l.includes('Complete')) || 'Export complete!';
        btn.textContent = summary.slice(0, 45);
        btn.style.background = '#4caf50';
      }} else {{
        btn.textContent = 'Failed — check console';
        btn.style.background = '#f44336';
        console.error('Export output:', outputLines.join('\\n'));
      }}
      setTimeout(() => {{
        btn.textContent = 'Export All to TEI';
        btn.style.background = '#0d7377';
        btn.disabled = false;
      }}, 4000);
    }})
    .catch(e => {{
      btn.textContent = 'Error!';
      btn.style.background = '#f44336';
      console.error('Export failed:', e);
      setTimeout(() => {{
        btn.textContent = 'Export All to TEI';
        btn.style.background = '#0d7377';
        btn.disabled = false;
      }}, 3000);
    }});
}}

// ── Stats ────────────────────────────────────────────────
function updateStats() {{
  const total = CANDIDATES.length;
  const vals = Object.values(candidateDecisions);
  const accepted = vals.filter(d => d.action === 'accepted').length;
  const rejected = vals.filter(d => d.action === 'rejected').length;
  const merged = vals.filter(d => d.action === 'merged').length;
  const reassigned = vals.filter(d => d.action === 'reassigned').length;
  const persons = vals.filter(d => d.action === 'person').length;
  const places = vals.filter(d => d.action === 'place').length;
  const orgs = vals.filter(d => d.action === 'org').length;
  const reclassified = persons + places + orgs;
  const pending = total - accepted - rejected - merged - reassigned - reclassified;

  let stats = `${{total}} candidates · ${{pending}} pending · ${{accepted}} accepted · ${{rejected}} rejected · ${{merged}} merged`;
  if (reassigned > 0) stats += ` · ${{reassigned}} reassigned`;
  if (reclassified > 0) {{
    const parts = [];
    if (persons) parts.push(`${{persons}} people`);
    if (places) parts.push(`${{places}} places`);
    if (orgs) parts.push(`${{orgs}} orgs`);
    stats += ` · ${{parts.join(', ')}}`;
  }}
  document.getElementById('headerStats').textContent = stats;
}}

// ── Helpers ─────────────────────────────────────────────
function escapeHtml(str) {{
  const div = document.createElement('div');
  div.textContent = str;
  return div.innerHTML;
}}

function debounce(fn, ms) {{
  let timer;
  return (...args) => {{ clearTimeout(timer); timer = setTimeout(() => fn(...args), ms); }};
}}

// ── Start ────────────────────────────────────────────────
init();
</script>
</body>
</html>"""

    return html


def build_category_html(category, categories, subjects):
    """Build an HTML review file for a single category."""
    candidates = load_category_candidates(category)
    if not candidates:
        return

    title = CATEGORY_TITLES[category]
    state_key = CATEGORY_STATE_KEYS[category]
    output_file = CATEGORY_OUTPUT_FILES[category]

    # Compute merge suggestions for this category's candidates
    print(f"  Computing merge suggestions against {len(subjects)} taxonomy terms...")
    merge_suggestions = compute_merge_suggestions(candidates, subjects)
    matched = len(merge_suggestions)
    total_suggestions = sum(len(v) for v in merge_suggestions.values())
    print(f"  {matched} candidates have suggestions ({total_suggestions} total matches)")

    print(f"Building {category} HTML ({len(candidates)} candidates)...")
    html = build_html(candidates, categories, subjects,
                      title=title, state_key=state_key,
                      current_category=category,
                      merge_suggestions=merge_suggestions)

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(html)
    print(f"  Wrote {output_file} ({len(html):,} bytes)")


def main():
    parser = argparse.ArgumentParser(
        description='Build candidate review HTML files.')
    parser.add_argument(
        '--category',
        choices=['persons', 'organizations', 'topics', 'all'],
        default=None,
        help='Build a category-specific review file. '
             'Use "all" to build all three. '
             'Omit to build the combined legacy file.')
    args = parser.parse_args()

    print("Loading taxonomy categories...")
    categories, subjects = load_taxonomy_categories()
    print(f"  {len(categories)} categories, {len(subjects)} existing subjects")

    if args.category == 'all':
        # Build all three category-specific files
        for cat in ('persons', 'organizations', 'topics'):
            build_category_html(cat, categories, subjects)
    elif args.category:
        # Build a single category file
        build_category_html(args.category, categories, subjects)
    else:
        # Legacy combined mode
        print("Loading candidates (combined)...")
        candidates = load_candidates()
        print(f"  {len(candidates)} total candidates")

        index_count = sum(1 for c in candidates if c['source'] == 'index')
        lcsh_count = sum(1 for c in candidates if c['source'] == 'lcsh')
        print(f"  {index_count} from Index (Tier 2), {lcsh_count} from LCSH (Tier 3)")

        print("Building HTML...")
        html = build_html(candidates, categories, subjects)

        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write(html)
        print(f"Wrote {OUTPUT_FILE} ({len(html):,} bytes)")


if __name__ == '__main__':
    main()
