#!/usr/bin/env python3
"""
Enrich Airtable-sourced annotation results with sentence context.

For volumes where annotations were imported from Airtable (rather than
generated by string matching), the match entries have empty `sentence`
fields and `position` = 0. This script looks up each matched_text in
the actual document XML and fills in the sentence context and position,
preserving all existing match decisions.

Usage:
    python3 scripts/enrich_sentence_context.py
    python3 scripts/enrich_sentence_context.py frus1981-88v04 frus1977-80v17p3
"""

import json
import os
import re
import sys

# Import text extraction functions from annotate_documents
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from annotate_documents import extract_body_text, extract_sentence

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Volumes known to be Airtable-sourced (no sentence context)
AIRTABLE_VOLUMES = [
    "frus1977-80v11p1",
    "frus1977-80v17p3",
    "frus1977-80v19",
    "frus1977-80v23",
    "frus1977-80v24",
    "frus1981-88v04",
    "frus1981-88v05",
    "frus1981-88v06",
    "frus1981-88v11",
    "frus1981-88v41",
]


def load_document_text(volume_id, doc_id):
    """Load and cache extracted body text for a document."""
    doc_path = os.path.join(BASE_DIR, "data", "documents", volume_id, f"{doc_id}.xml")
    if not os.path.exists(doc_path):
        return ""
    text, _ = extract_body_text(doc_path)
    return text


def find_match_in_text(text, matched_text):
    """Find matched_text in document text, case-insensitive with word boundaries.

    Returns (position, sentence) or (0, "") if not found.
    """
    if not text or not matched_text:
        return 0, ""

    try:
        pattern = re.compile(
            r"(?<!\w)" + re.escape(matched_text) + r"(?!\w)",
            re.IGNORECASE,
        )
        m = pattern.search(text)
        if m:
            sentence = extract_sentence(text, m.start(), m.end())
            return m.start(), sentence
    except re.error:
        pass

    return 0, ""


def enrich_volume(volume_id):
    """Enrich sentence context for a single volume's results.

    Returns (enriched_count, total_count) or None on error.
    """
    results_path = os.path.join(
        BASE_DIR, "data", "documents", volume_id,
        f"string_match_results_{volume_id}.json"
    )

    if not os.path.exists(results_path):
        print(f"  ERROR: Results file not found: {results_path}")
        return None

    with open(results_path) as f:
        data = json.load(f)

    # Cache document texts to avoid re-parsing
    doc_text_cache = {}
    enriched_count = 0
    not_found_count = 0
    total_count = 0

    # Collect all unique doc_ids we need to process
    all_doc_ids = set()
    for ref, term_data in data["by_term"].items():
        for doc_id in term_data["documents"]:
            all_doc_ids.add(doc_id)

    # Enrich by_term entries
    for ref, term_data in data["by_term"].items():
        for doc_id, matches in term_data["documents"].items():
            # Load document text (cached)
            if doc_id not in doc_text_cache:
                doc_text_cache[doc_id] = load_document_text(volume_id, doc_id)
            text = doc_text_cache[doc_id]

            for match in matches:
                total_count += 1
                if match.get("sentence"):
                    # Already has context, skip
                    continue

                matched_text = match.get("matched_text", "")
                position, sentence = find_match_in_text(text, matched_text)

                if sentence:
                    match["sentence"] = sentence
                    match["position"] = position
                    enriched_count += 1
                else:
                    not_found_count += 1

    # Enrich by_document entries to match
    for doc_id, doc_data in data["by_document"].items():
        if doc_id not in doc_text_cache:
            doc_text_cache[doc_id] = load_document_text(volume_id, doc_id)
        text = doc_text_cache[doc_id]

        for match in doc_data.get("matches", []):
            if match.get("sentence"):
                continue

            matched_text = match.get("matched_text", "")
            position, sentence = find_match_in_text(text, matched_text)

            if sentence:
                match["sentence"] = sentence
                match["position"] = position

    # Write back
    with open(results_path, "w") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"  Enriched: {enriched_count}/{total_count} matches")
    if not_found_count:
        print(f"  Not found in text: {not_found_count} (preserved as-is)")

    return enriched_count, total_count


def main():
    if len(sys.argv) > 1:
        volumes = sys.argv[1:]
    else:
        volumes = AIRTABLE_VOLUMES

    print(f"Enriching sentence context for {len(volumes)} volume(s)...\n")

    total_enriched = 0
    total_matches = 0

    for volume_id in volumes:
        print(f"Processing {volume_id}...")
        result = enrich_volume(volume_id)
        if result:
            enriched, total = result
            total_enriched += enriched
            total_matches += total

    print(f"\n{'=' * 60}")
    print(f"Done. Enriched {total_enriched}/{total_matches} matches across {len(volumes)} volumes.")


if __name__ == "__main__":
    main()
